### PR TITLE
Added option to open lightbox from JavaScript directly

### PR DESCRIPTION
**Pull request by cenharmonic**

### CODE REVIEW

**Comment by darkylmnx** [comment]
hi, nice idea, could you just remove the requestAnimationFrame, i think it's not necessary here.

You should execute the open function in the iframe loaded callback instead and create a seperate function for this callback instead of an anonymous function :)

**Comment by cenharmonic** [comment]
Sure! I'll update that - I found a bug with it too (old lightboxes aren't destroyed or reused when opened this way since they're not bound to an element, so sometimes the video keeps playing in the background), so I'll fix that while I'm at it. :)

**Comment by cenharmonic** [comment]
I'll make a new pull request and close this one. Thanks again!

**Comment by darkylmnx** [comment]
no prob :)

**Comment by cenharmonic** [comment]
Looks like I have to reopen it if it's on the same branch. XD New to this!

**Comment by darkylmnx** [comment]
oh i see something quite wrong in the demo
`
$(".play-5").click( function() {
      $.fn.yu2fvl({ vid: "AbTUw7aTITg", ratio: 21/9, open: true });
    });
`

this means it opens on click, so the open:true option here will be useless.

I think we should always bound to an element and just auto open when the person needs it because, if you close the ligthbox, you may want to re-open this same lightbbox with a button within the page.

Also, using : $.fn.yu2fvl ... directly is not a good practive it must always be $(...).yu2fvl or $.yu2fvl 

So i'll add this too, you can check it on the next commit. Nice job by the way :+1:

**Comment by cenharmonic** [comment]
Oh! That makes total sense. :) Thanks for the help and working with me!

**Comment by darkylmnx** [comment]
no prob

**Pull request merged**
